input_task:
  description: >
    Receive the topic and prepare the workflow for execution.
  expected_output: >
    A confirmation and structured version of the input topic.
  agent: input_agent

keyword_task:
  description: >
    Extract or generate the 5-10 most relevant keywords for {topic}. Validate them with Pydantic to ensure
    they are unique, relevant, and non-empty.
  expected_output: >
    A validated list of 5-10 keywords.
  agent: keyword_agent

story_task:
  description: >
    Use the validated keywords to write a structured, engaging, and informative story/article about {topic}.
  expected_output: >
    A story or article formatted in markdown without code fences.
  agent: story_agent

evaluation_task:
  description: >
    Review the story for quality, factual accuracy, clarity, and logical flow. Suggest improvements if necessary.
  expected_output: >
    A markdown evaluation report highlighting strengths, weaknesses, and corrections.
  agent: evaluation_agent

reporting_task:
  description: >
    Collect outputs from all agents, evaluate the workflows performance, and generate a final markdown report file.
  expected_output: >
    A final report that summarizes the topic, the workflow steps, and the final outputs.
  agent: reporting_agent
