research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is {current_year}.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic}
  agent: researcher

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledged report with the main topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst

summarization_task:
  description: >
    Summarize the research and report findings on {topic} into a concise overview.
    Highlight only the most important points so it's easy to digest quickly.
  expected_output: >
    A short markdown summary (max 1 page) covering the main insights about {topic}.
  agent: summarizer

error_detection_task:
  description: >
    Review the research and reports about {topic} carefully to identify any
    errors, inconsistencies, or logical flaws.
  expected_output: >
    A markdown list of detected errors, contradictions, or weak arguments,
    with suggested corrections.
  agent: error_detector